spring:
  datasource:
    url: jdbc:h2:file:./camunda-recommendation-h2-database
  jpa:
    hibernate:
      ddl-auto: create-drop

zeebe:
  client:
    cloud:
      cluster-id: <your cluster ID>
      client-id: <your client ID>
      client-secret: <you secret>

server:
  port: 8081