camunda.bpm:
  default-serialization-format: application/json
  metrics.enabled: false
  client:
    base-url: http://localhost:8081/engine-rest
    async-response-timeout: 10000
    worker-id: sendNotificationWorker-1
  generic-properties:
    properties:
      initializeTelemetry: false
